src/App.jsx, src/components/matching/MainMatching.jsx
1. 검색시 마커 인포윈도우 디자인 수정하였습니다.
2. 입력된 키워드로 검색할 수 있게끔 구현하였습니다.
=> Feat: 추가 입력된키워드 범위 내 검색

src/components/layout/Header.jsx
=> design : header 위치 조정

src/components/matching/MainMatching.jsx
1. 인포윈도우에서 선택할 수 있는 버튼을 우선 추가해두었습니다.
2. 선택 시 표시된 마커 삭제하고 선택한 마커만 보이도록 처리하였습니다.
3. 선택 시 input 필드 비활성화 시켰습니다.
4. 선택 시 인포윈도우에서 재선택 할 수 있는 버튼을 우선 추가해두었습니다.
=> Feat: 추가 장소선택 함수

package-lock.json, src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx, src/views/MyPage.jsx, yarn.lock
1. 마이페이지 레이아웃 퍼블리싱 
식당정보 컴포넌트 화면 퍼블리싱 완료
- 메달 물음표 호버시 안내문 표시
매칭 히스토리 컴포넌트 표시 화면 퍼블리싱 완료
=> design : 마이페이지 퍼블리싱

src/components/rests/RestInfo.jsx
변경 클릭 시 닉네임 및, 한 줄 소개 변경 할 수 있도록 추가
=> feat : 마이 페이지 닉네임,한 줄 소개 변경 기능

package.json, src/components/account/ChangePW.jsx, src/components/account/DeleteID.jsx, src/components/notice/SuccessNotice.jsx, src/components/rests/RestInfo.jsx, src/router/router.jsx
=> feat : 닉네임 변경 버튼 오류 수정

src/components/matching/InfoWindow.jsx, src/components/matching/MainMatching.jsx, src/components/matching/SearchList.jsx
1. geo...api 정확도부분 수정하는 코드 추가하였습니다. 추가하면서 error 핸들링 할 수 있게 변경하였습니다.
2. 리스트에서 장소 클릭시 마커의 인포윈도우가 열리도록 수정하였습니다.
3. 인포윈도우 부분 컴포넌트화 시켰습니다.
=> Refactor: 변경 매칭 인포윈도우 컴포넌트

package-lock.json, package.json, src/components/matching/Matching.jsx, src/router/router.jsx, src/views/Matching.jsx, yarn.lock
1. /matching 라우트 임의로 생성해서 매칭중 페이지 퍼블리싱 진행했습니다.
=> Design: 추가 매칭중UI

src/components/common/TwoBtnModal.jsx, src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx
차단하기, 신고하기 클릭 시 예 아니요 선택 모달 창 뜨도록 구현했습니다.
=> Feat : 추가 모달 창 관련 기능

src/components/matching/MainMatching.jsx, src/main.jsx
1. 창 이동시 마커가 초기화 되는 문제 해결하였습니다.
=> Fix: 고침 창 이동시 마커 초기화 문제

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx
=> Feat: 추가 모달 창 기능

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx
모달 외부 클릭 시 닫는 코드
useRef로 통일해서 사용하도록 변경
=> Refactor: 변경 모달 창 닫기 기능

src/App.css, src/components/matching/AgreePlace.jsx, src/components/matching/CheckPlace.jsx, src/components/matching/InfoWindow.jsx, src/components/matching/MainMatching.jsx, src/router/router.jsx
우선 브랜치 새로 만들고 옮기고 작업했어야 하는데 실수했습니다. 죄송합니다.
1. 장소 확인페이지
2. 장소 선택페이지
퍼블리싱 했습니다.
=> Design: 추가 장소확인, 장소선택 UI

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/rests/RestReviews.jsx
=> Feat: 추가 차단, 신고 기능

src/components/rests/WriteReview.jsx, src/router/router.jsx
=> Design: 추가 매칭완료

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/rests/RestReviews.jsx
=> Feat: 추가 신고,차단 해제

src/components/rests/RestReviews.jsx
1. 차단, 신고시 state 로 관리하여 리렌더링 되도록 코드 변경하였습니다.
2. 관련해서 로컬스토리지 사용 할 필요 없이 초기 렌더링시 api 호출하여 데이터를 로드하도록 추후 코드 수정하면 될 것 같습니다.
=> Fix: 변경 매칭히스토리 차단,신고

src/components/matching/CheckPlace.jsx, src/components/matching/InfoWindow.jsx, src/components/matching/MainMatching.jsx, src/mocks/matching/completeMatching.json
1. 장소선택시 새로고침 방지 코드 넣었습니다.
2. 장소선택시 타이머 완료 후 메인화면으로 넘어갑니다.
=> Feat: 추가 장소선택페이지 새로고침 방지

src/components/account/Login.jsx, src/components/account/SignUp.jsx, src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/layout/Header.jsx, src/mocks/handler.jsx
1. 로그인 시 생성된 토큰을 저장한 로컬 스토리지를 확인합니다.
2. 토큰이 존재하면 헤더에 로그아웃 표시를 하도록 했습니다.
3. 로그아웃 시 서버에 빈 토큰 값을 보내고 응답 성공시 로컬스토리지에 저장된 토큰값을 삭제합니다. 
4 삭제되면 헤더에는 다시 로그인으로 표시가 됩니다.
=> Feat: 추가 헤더 로그인 상태 표시

src/components/matching/MainMatching.jsx, src/mocks/matching/completedMatching.json
=> Fix: 변경 새로고침이벤트

src/components/account/Login.jsx, src/components/account/SignUp.jsx, src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/layout/Header.jsx, src/components/matching/MainMatching.jsx, src/components/matching/MatchingComplete.jsx, src/mocks/handler.jsx
1. 소셜 로그인 (네이버, 카카오) 구현했습니다.
2. 로그인 시 헤더 에 마이페이지로 가는 버튼이 보이도록 수정했습니다.
=> Feat: 추가 소셜 로그인

.gitignore, .vscode/extensions.json, .vscode/settings.json, src/components/rests/WriteReview.jsx, src/mocks/handler.jsx, src/mocks/rests/restList.json, src/mocks/rests/restReviewList.json
=> Feat: 추가 리뷰작성

src/components/layout/Header.jsx, src/components/matching/InfoWindow.jsx, src/components/matching/MainMatching.jsx
1. 메인페이지 헤더 로그인상태에따라 변경되도록 조정했습니다.
2. 비로그인시 매칭 불가능하게 변경했습니다.
=> Feat: 추가 메인페이지 헤더 로그인상태, 로그인X -> 매칭불가능

src/components/common/OneBtnModal.jsx, src/components/layout/Header.jsx, src/components/rests/RestInfo.jsx, src/mocks/handler.jsx, src/mocks/mypage/profile.json, src/router/router.jsx
1. 로그인 후 마이페이지 클릭 시 /mypage로 이동 후 서버에서 프로필 정보를 확인 후 /mypage/:id 값주소로 변경되고 보여집니다.
2. 닉네임 및 한 줄 소개를 변경하면 서버로 변경정보를 저장하고 저장된 닉네임과 한줄소개를 가져오도록 했습니다.
=> Feat: 추가 프로필 정보 가져오기, 닉네임, 한 줄 소개 변경 서버 전송

package-lock.json, package.json, src/components/rests/RestList.jsx, src/components/rests/RestView.jsx, src/mocks/handler.jsx, src/mocks/rests/restList2.json, src/mocks/rests/restList3.json, yarn.lock
1. position absolute -> fixed 로 변경하여 스크롤하고 모달 오픈시 모달위치가 맞지 않았던 문제 해결하였습니다.
=> Fix: 변경 식당상세조회 모달 위치

src/components/account/ChangePW.jsx, src/components/account/SignUp.jsx, src/components/rests/RestInfo.jsx, src/mocks/handler.jsx
1. 비밀번호 변경 MSW 목데이터 활용해 구현했습니다.
2. 확인을 위해 현재 비밀번호는 임시로 1234로 고정 시켜 두었습니다.
=> Feat: 추가 비밀번호 변경

src/components/account/ChangePW.jsx, src/components/account/DeleteID.jsx, src/mocks/handler.jsx
1. 탈퇴하기 버튼을 클릭한 뒤 예를 누르면 /users/withdrawal 로 delete 매소드 요청을 보내고 응답을 받는 구조를 만들었습니다.
=> Feat: 추가 탈퇴하기 MSW

src/components/matching/MainMatching.jsx, src/components/matching/MatchingComplete.jsx, src/components/rests/WriteReview.jsx, src/mocks/matching/completedMatching.json
1. 리뷰작성페이지 UI 수정하였습니다.
2. navigate 의 state 활용하여 페이지 이동시 데이터 주고받을 수 있도록 했습니다.
=> Feat, Design: 추가 리뷰작성 UI, navigate함수

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/layout/Header.jsx, src/components/matching/CheckPlace.jsx, src/components/matching/InfoWindow.jsx, src/components/matching/MainMatching.jsx, src/components/matching/Matching.jsx, src/components/matching/MatchingComplete.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestReviews.jsx, src/mocks/matching/completedMatching.json, src/store/modalStore.js
1. 모달 컴포넌트는 메세지 확인 용으로 사용하기 위해 수정했습니다.
매칭 취소 모달, 검색어 비었을 때 모달, 비로그인 시 매칭 클릭 시 모달
나의 방문기록 차단 신고 버튼 클릭 시 모달 
2. 현재 작성하고 있는 곳에서 원히는 모달 관련 속성을 변경할 수 있습니다.
=> Refactor: 변경 모달 컴포넌트

src/components/account/Login.jsx
=> Fix: 수정 로그인

src/components/layout/Header.jsx, src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/components/matching/MainMatching.jsx, src/components/matching/MatchingComplete.jsx, src/components/notice/SuccessNotice.jsx, src/mocks/handler.jsx, src/mocks/matching/agreeUser4.json, src/mocks/matching/completedMatching.json
1. 모임 생성 완료된 후 3분이내 이탈자 발생 상황을 setTimeout 10초로 가정하여 구현하였습니다.
=> Feat: 추가 모임생성후 3분이내 이탈자 발생 함수

src/components/matching/CheckPlace.jsx, src/components/rests/RestList.jsx
=> Design: 수정 레이아웃

handler.jsx, src/components/account/SignUp.jsx, src/components/common/OneBtnModal.jsx, src/components/layout/Header.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestReviews.jsx, src/mocks/handler.jsx
1. 회원가입 완료 시 모달 창 잘못 표시되는 부분 수정하였습니다.
2. 오타 수정하였습니다.
3. 버튼 한개 있는 모달 컴포넌트 파일 을 변경하였습니다.
- 기존 확인 버튼을 클릭하면 모달이 닫히는 기능만 있음
- 확인 버튼 클릭 시 onConfirm 변수 사용
- 모달을 표시하는 코드를 사용하는 파일에서 모달 관련 추가 동작 구현 가능
=> Fix: 수정 회원가입 완료 모달 창

package-lock.json, package.json, src/App.css, src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/components/matching/Matching.jsx, src/mocks/matching/completedMatching.json, yarn.lock
1. 매칭중에는 뒤로가기가 불가능하도록,
2. 임시 모임이 생성된 후에는 뒤로가기 선택시 모임 취소 api를 호출하도록, 
3. 모임이 생성된 후에는 뒤로가기 선택시 main으로 이동하도록 변경하였습니다.
=> Feat: 추가 매칭시작후 뒤로가기 방지

src/App.css, src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/mocks/matching/completedMatching.json
1. place-items-center가 모바일에서 적용되지 않아 변경하였습니다.
=> Fix: 변경 place-items-center

src/components/matching/CheckPlace.jsx, src/components/matching/MainMatching.jsx, src/components/matching/Matching.jsx, src/components/matching/MatchingComplete.jsx, src/components/rests/RestList.jsx, src/components/rests/WriteReview.jsx
1. 매칭, 내돈내산맛집부분 axios 요청 url 환경변수 사용할 수 있도록 수정하였습니다.
=> Fix: 변경 axios요청 url

package-lock.json, package.json, src/components/matching/CheckPlace.jsx, src/components/matching/Matching.jsx, src/components/matching/MatchingComplete.jsx, src/components/rests/WriteReview.jsx, yarn.lock
=> Fix: 변경 SSE구독 함수

src/components/matching/MainMatching.jsx, src/components/matching/Matching.jsx
=> CSS: 모바일 마커 클릭

src/components/matching/MainMatching.jsx
=> CSS: 변경 마커인포윈도우 위치

package-lock.json, package.json, src/components/account/DeleteID.jsx, src/components/account/Login.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx, src/store/profile.js
1. 프로필 정보 mobx로 전역관리 하도록 구현하였습니다.
2. 마이페이지 클릭 시 현재 로그인 한 사용자의 정보를 보여줍니다.
3. vercel 환경변수도 변경했습니다.
4. 탈퇴하기 클릭 시 모달로 표시하도록 변경했습니다.
5. 모달 컴포넌트 메세지 보내는 부분 함수 형식으로 보낼 수 있도록 변경했습니다.
=> Fix: 변경 마이페이지 프로필정보

src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/modal/ModalContainer.jsx, tailwind.config.js
1. 모달 창 UI 수정했습니다.
2. 기본 색상 추가했습니다. primary: "#FF6445", -> 메인 주황색
secondary: "#A2A2A2" -> 네거티브 속성
=> Design: 수정 모달

package-lock.json, package.json, src/components/common/OneBtnModal.jsx, src/components/common/TwoBtnModal.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestInfo.jsx, src/index.css, tailwind.config.js, yarn.lock
Design: 수정 모달
1. 모달 창 UI 수정했습니다.
2. 기본 색상 추가했습니다. primary: "#FF6445", -> 메인 주황색
secondary: "#A2A2A2" -> 네거티브 속성
-----------------------------------
Design: 추가 버튼 반응
1. framer-motion 사용해 버튼 반응을 구현했습니다.
2. 기본 색상 루트 추가 및 수정했습니다.
3.  프로필 수정 버튼 클릭 후 변경 안하고 완료하면 오류 나던거 수정했습니다.
=> Design: 수정 모달 및 버튼 반응

src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/components/matching/Matching.jsx, src/components/matching/MatchingComplete.jsx, src/components/rests/WriteReview.jsx, src/mocks/matching/completedMatching.json
=> Fix: 변경 CSS 모바일

src/components/account/ChangePW.jsx, src/components/rests/RestInfo.jsx
=> Fix: 수정 회원탈퇴, 비밀번호 변경

src/components/rests/RestList.jsx, src/components/rests/WriteReview.jsx
1. 작성완료시 메인페이지로 옮길 수 있도록 했습니다.
=> Feat: 추가 작성완료 navigate

src/components/account/ChangePW.jsx, src/components/account/Login.jsx, src/components/common/TwoBtnModal.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestInfo.jsx, src/index.css, tailwind.config.js
1. 회원탈퇴 버튼 위치 반대로 보이도록 수정했습니다.
2. 회원탈퇴 예를 클릭 시 한번 더 물어보는 모달을 추가했습니다.
3. 마이페이지에 비밀번호 변경, 탈퇴하기 버튼 클릭 시
&& 모달 창 버튼 클릭 시 테스트 반응을 추가했습니다.
=> Fix: 변경 & 추가 회원탈퇴 버튼 위치 & 추가 모달 & 버튼 반응

src/App.jsx, src/components/account/ChangePW.jsx, src/components/account/Login.jsx, src/components/account/SignUp.jsx, src/components/common/ErrorMessage.jsx, src/components/layout/Header.jsx, src/mocks/login/userList.json
1. 모바일 화면 사이즈 조절 했습니다.
2. input 내용 전체 삭제하는 버튼 추가했습니다.
3. 로그인 회원가입 관련 에러 메세지 컴포넌트를 추가 했습니다.
4. 에러메세지 표시할 때 인터렉티브 효과 적용했습니다.
5. 첫 로그인 시 마이페이지로 가도록 하는 모달 창 추가했습니다.
=> Fix: 로그인 회원가입 UI

src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/components/matching/MainMatching.jsx, src/components/matching/Matching.jsx, src/components/matching/MatchingComplete.jsx, src/mocks/matching/completedMatching.json, src/store/matchingStore.js
1. 매칭관련해서 mobX로 상태관리 할 수 있도록 추가했습니다.
2. 추후 로그인시 매칭데이터 불러오는 함수 추가하도록 하겠습니다.
=> Feat: 추가 매칭관련 mobX 상태관리

src/components/matching/MainMatching.jsx
1. sm이하 사이즈일때는 내 위치로 이동 아이콘을 조금 작게 보이도록 변경하였습니다.
=> CSS: 변경 sm 아이콘 사이즈

src/components/common/TwoBtnModal.jsx, src/components/rests/RestInfo.jsx, src/components/rests/RestList.jsx, src/components/rests/RestView.jsx
1. 박스 사이즈에 꽉 차게 사진 보이도록 수정
2. 모달 창 닫기 버튼 위치 수정
3. 스크롤 박스 경계선 추가
=> Design: 수정 식당 게시판 수정

src/components/matching/ChoicePlace.jsx, src/components/matching/MatchingComplete.jsx
=> Fix: 변경 변수명

src/components/layout/Header.jsx
=> Fix: 네이버 로그아웃

src/components/rests/RestReviews.jsx, src/mocks/mypage/historyApi.json, src/mocks/mypage/historyApi2.json, src/views/MyPage.jsx
1. 신고, 모달 창 표시 위치 수정
2. 신고 api명세서 수정 반영
=> Fix 수정 마이페이지

src/components/hooks/useAxios.jsx, src/components/matching/MainMatching.jsx, src/components/rests/RestReviews.jsx
Axios 커스텀훅을 생성하였습니다.
사용 예제
```
const getProfile = async () => {
const resProfile = await callApi("/users/profile", "GET");
console.log(resProfile.data);
if (resProfile.data !== undefined) {
if (resProfile.data.penalty)
window.sessionStorage.setItem("isPenalty", true);
else {
window.sessionStorage.setItem("isPenalty", false);
getMatching();
}
}
};
```
=> Feat: 추가 Axios 커스텀훅

src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx, src/mocks/mypage/historyApi.json
=> FIx: 수정 마이페이지

src/components/rests/RestInfo.jsx, src/components/rests/RestReviews.jsx, src/mocks/mypage/historyApi.json
1. 리뷰 작성 페이지 전달하는 값 수정
2. 취소된 매칭 구분
=> Fix: 수정 마이 페이지

src/components/hooks/useInterval.jsx, src/components/matching/MainMatching.jsx, src/components/matching/MatchingComplete.jsx
1. 매칭 완료 페이지에서 1분마다 지난 시간을 계산하는 함수를 호출하여 1시간 경과시 리뷰페이지로 이동하도록 하였습니다.
2. 지금은 임시로 2분뒤에 이동하도록 수정하였습니다.
=> Feat: 추가 useInterval을 이용해 1분마다 시간체크

src/components/matching/CheckPlace.jsx, src/components/matching/MainMatching.jsx, src/components/matching/MatchingComplete.jsx, src/components/rests/RestReviews.jsx, src/components/rests/WriteReview.jsx
1. 리뷰작성시 이미지 업로드 부분 수정했습니다.
2. navigate할 때 matchingHistoryId값을 보내도록 수정했습니다.
3.
=> Fix: 리뷰작성 이미지업로드, navigate state

src/components/rests/RestReviewItem.jsx
1. 응답 받는 api url 네이밍으로 수정하였습니다.
2. 작성 시간 분까지만 표시
=> Fix: 수정 리뷰확인

src/App.css, src/components/matching/MatchingComplete.jsx
1. 매칭 이탈자 발생시 모달 표시 하도록 변경
2. 클릭시 불필요한 곳 커서 안생기도록 수정
=> Fix: 수정 매칭 이탈자 모달

src/components/matching/MainMatching.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/WriteReview.jsx
1. 모달창 위치값 변경했습니다.
2. 패널티 api이름 변경했습니다.
3. 사진 삭제 버튼 수정했습니다.
=> Fix: 수정 모달, 패널티, x표시

src/components/account/Login.jsx, src/components/common/OneBtnModal.jsx, src/components/matching/CheckPlace.jsx, src/components/matching/ChoicePlace.jsx, src/components/matching/MainMatching.jsx, src/components/modal/ModalContainer.jsx, src/components/rests/RestInfo.jsx
1. 이동 주소는 매칭히스토리ID값을 보이도록 변경했습니다
2. 모달 창 뒷배경을 클릭해도 모달이 닫히지 않는 함수를 추가했습니다.
( 뒷배경을 클릭해도 화면이 안닫히려면 backgroundClickNoClose: true 만 추가로 넣어주시면 됩니다.)
사용 예시 
modalStore.openModal("oneBtn", {
message: "탈퇴하기 완료.",
onConfirm: async () => {
await modalStore.closeModal();
localStorage.removeItem("token");
authStore.setLoggedIn(false);
navigate("/");
},
backgroundClickNoClose: true
});
console.log("탈퇴하기 완료");
}
3. 버튼 1개 인 모달 버튼 클릭 효과 추가 했습니다.
=> Fix: 매칭히스토리 이름
